# Default values for marketsummary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image: marketsummary:latest
version: "0.0.1-SNAPSHOT" 
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
workload: springtrader

service:
  type: ClusterIP
  port: 8080

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  cpu: 80
  memory: 512Mi
  requests:

canary:
  enabled: true
  progressDeadlineSeconds: 60
  istioIngress:
    enabled: true
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5  
  # names of metrics
  metrics:
    successRate: request-success-rate
    latency: request-duration
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: false
    # load tester address
    url: http://flagger-loadtester.test/

istioDomain: ""
  
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 8m
    memory: 768Mi
  requests:
    cpu: 4m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

