apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: marketsummary
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary
        chartPath: ./charts/marketsummary
        values:
          image: marketsummary
        setValues:
          hpa.enabled: true
          canary.enabled: true
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
